### PR TITLE
2D expansion to IEM module

### PR DESCRIPTION
**Pull request by vyaivo**
This is an initial PR so that the code co-authors can review it and make changes to the example notebook and docstrings.

Even if we only need minimal changes to `iem.py`, I still need to write many unit tests for the new code. I also have not done any final formatting checks using the shell scripts.

@mihaic, can you add @JamesWardAntony and @dhuberdeau as reviewers?

### CODE REVIEW

**Comment by mihaic** [comment]
@JamesWardAntony, @dhuberdeau, you should see a "Review changes" button in the "Files changed" tab:
https://github.com/brainiak/brainiak/pull/482/files

**Review by JamesWardAntony — APPROVED** [review]

**Comment by mihaic** [comment]
I find the Codecov "Details" link confusing. You can see what lines are not covered in the Codecov pull request interface:
https://codecov.io/gh/brainiak/brainiak/pull/482/diff

**Comment by mihaic** [comment]
@vyaivo, should we merge this PR?

**Comment by vyaivo** [comment]
I'm doing a final review now this afternoon will remove the WIP/draft status when I've finished.

**Comment by vyaivo** [comment]
@JamesWardAntony, I added another scoring function to the `InvertedEncoding2D` class, and made some changes that made the test coverage more accurate / complete. I also made some minor text changes to the example.

You are welcome to look at the unit tests but no need to review them.
Once you look at the new changes and approve, I think we should be good to merge!

**Review by JamesWardAntony — APPROVED** [review]
Looks great, Vy!!

**Review by mihaic — APPROVED** [review]

**Comment by mihaic** [comment]
Thank you for this substantial contribution, @vyaivo & @JamesWardAntony!

**Pull request merged**
