### PR TITLE
Update ISC permutation doc to clarify pairwise groups

### PR DESCRIPTION
**Pull request by snastase**
This addresses the confusion with issue #449 (via @mcdoar9). The documentation was unclear on how to supply pairwise ISCs for two groups to the permutation test. The documentation is now updated to make it more clear that pairwise ISCs must be computed on both groups at once (such that between-group ISCs are included in the pairwise ISC matrix) prior to this ISC matrix being supplied to `permutation_isc`.

### CODE REVIEW

**Comment by snastase** [comment]
Oops accidentally created this branch off the [`isc-boot-fix`](https://github.com/snastase/brainiak/tree/isc-boot-fix) branch at PR #475. Hopefully won't cause problems...?

**Comment by CameronTEllis** [comment]
Great, Tristan volunteered for this

**Comment by snastase** [comment]
@tristansyates good point! I fixed the tense. I think I'll leave the somewhat redundant input shape descriptions... the earlier one is intended to clarify that pairwise ISCs should have been computed in such a way as to produce a distance matrix containing both groups; the latter more specifically describes the input shapes (which for the pairwise approach should be distance vectors, not square).

**Comment by mihaic** [comment]
@snastase, the current changes look off. If you try to fix the code, start with a pull from GitHub because I used the update branch from master button.

**Comment by snastase** [comment]
> @snastase, the current changes look off. If you try to fix the code, start with a pull from GitHub because I used the update branch from master button.

@mihaic—not sure I totally understand. Does something in particular look off to you? It looks correct to me... The only weirdness is that the changes from #475 are also part of the diff here. If we merge #475, this will only have a small diff—i.e. the only real diff in this PR is the two added lines 1070-1071 in the docstring.

**Comment by mihaic** [comment]
I thought the main change of this PR was introduced in commit
https://github.com/brainiak/brainiak/pull/476/commits/8e557d48c54d6118e678415bc0f60930f95fa1b7

I thought that change was missing in the current diff. However, I noticed that change was actually merged with PR #477.

If you only need lines 1070-1071, we can merge them right away if you remove the changes from #475. Or we can wait for #475.

**Pull request merged**
