### PR TITLE
Implement release publishing

### PR DESCRIPTION
**Pull request by davidt0x**
This PR implements building of Anaconda and sdist packages for Python 3.8 through 3.10 and uploading to anconda.org and pypi.org on tagged releases. I tried to test the uploading piece as much as possible on my fork but it might need some fixes when it is triggered for the first time.

### CODE REVIEW

**Comment by mihaic** [comment]
This is great, @davidt0x! Is uploading to PyPI also coming in this PR?

**Comment by davidt0x** [comment]
Ok, sure, I can add it. sdist only correct?

**Comment by mihaic** [comment]
Yes, please. Only sdist.

On a different note, do you know why the main workflow is not triggered by this PR?

**Comment by davidt0x** [comment]
I am not sure why the workflow didn't run. It does say review required on my end so maybe since it is modifying the workflow it requires review first before running. The workflow ran on my for fine.

**Comment by davidt0x** [comment]
Actually, scratch that, I see the problem. I have a YAML syntax error after I uncommented the if statement. Let me fix.

**Review by mihaic — APPROVED** [review]

**Pull request merged**
