### PR TITLE
Using np.linalg.multi_dot

### PR DESCRIPTION
**Pull request by maldil**
I believe, it is more succinct and effective to refactor code to use np.linalg.multi_dot rather than numerous np.dot routines. Would you be willing to assist me in merging this PR?

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by mihaic** [comment]
Do you like this improvement proposal, @lcnature?

**Comment by lcnature** [comment]
Hi @maldil Thank you so much for the suggestion!
Sorry that I somehow entirely missed all the email notification - some stressing event happened around that time last year. 
I am totally up for this change. @mihaic Thanks for checking with me.

**Review by lcnature — APPROVED** [review]
All look good to me!

**Comment by mihaic** [comment]
Thank you for your contribution, @maldil!

**Pull request merged**
