### PR TITLE
Allowing the `sl_rad` parameter in searchlight to be 0

### PR DESCRIPTION
**Pull request by lcnature**
There are use cases in which we want to do the same processing on all voxels and want to use MPI to parallelize this. In this case, the searchlight has the size of 1, and it corresponds to `sl_rad = 0` when initializing `SearchLight`. But the current implementation will distribute an empty array to each worker if we set `sl_rad = 0`. The consequence is that nothing gets computed for each voxel. This PR fixes this bug.

### CODE REVIEW

**Comment by mihaic** [comment]
I hope the Conda build problem is intermittent and it will be gone on Monday. :) Will review then.

**Comment by CameronTEllis** [comment]
Happy to review this once those issues are resolved

**Comment by lcnature** [comment]
Awesome! @CameronTEllis you are welcome to review it as well. The changes are minor.

**Comment by mihaic** [comment]
@CameronTEllis, you can review; the errors are unrelated.

**Pull request merged**
