### PR TITLE
adding save/load functionality to funcalign/srm

### PR DESCRIPTION
**Pull request by me-sh**
Adding save/load functionality to funcalign/srm to resolve issue #428

### CODE REVIEW

**Comment by mihaic** [comment]
@me-sh, thank you for the PR! Please add tests. See the other SRM tests:
https://github.com/brainiak/brainiak/blob/master/tests/funcalign/test_srm.py
You can use the Pytest `tmp_path` fixture to obtain an output directory:
https://docs.pytest.org/en/latest/tmpdir.html#the-tmp-path-fixture

**Comment by snastase** [comment]
I made some minor adjustments and added a test of the SRM save/load functionality here: https://github.com/me-sh/brainiak/pull/1 (not sure how to commit changes more directly to this PR)

**Comment by mihaic** [comment]
Thanks, @snastase! You should be able to push your branch to @me-sh's.
```
git remote add me-sh https://github.com/me-sh/brainiak
git fetch me-sh
git push me-sh
```

**Comment by mihaic** [comment]
Because we are [planning to make a release](https://groups.google.com/g/brainiak/c/W9nBbTeFazY) very soon, I will add @snastase's commits to this PR and merge it.

**Comment by me-sh** [comment]
Thanks @snastase and @mihaic !

**Review by mihaic — APPROVED** [review]

**Comment by mihaic** [comment]
No, thank you, @me-sh! :)

And thanks for the quick help, @snastase.

**Pull request merged**
