### PR TITLE
[WIP] Add scripts to build Linux and MacOS wheels

### PR DESCRIPTION
**Pull request by danielsuo**
Very early work in progress, but we have successfully built wheels that install on fresh machines with no other dependencies. Many other issues to work through:

- [ ] How to handle the MPI dependencies (right now we package up an MPI wheel as well, but should include better logic for using existing MPI or mpi4py installations)
- [ ] Where and how to upload wheels (probably want to do this via travis when we release a new tag)
- [ ] End-to-end testing
- [ ] How do these wheels play with existing package / python installations

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by danielsuo** [comment]
I think there are two easy next steps:

1. Decide what we want the deployment flow to be and what the resulting user flow should be
2. Use a simple ```.travis.yml``` that only deals with building wheels to test everything

**Comment by mihaic** [comment]
Jenkins, OK to test.

**Comment by mihaic** [comment]
We can test on Conda using Jenkins. We need to make Jenkins wait for the wheels from Travis.

**Comment by danielsuo** [comment]
Why on Jenkins? (Don't know what our Jenkins test server is for) But I can
look into a Jenkins hook from Travis. Right now we're uploading the wheel
build artifacts into a publicly readable S3 bucket (s3://brainiak) on
successful build.

**Comment by mihaic** [comment]
Because Jenkins runs on infrastructure that we want to support: Conda, Slurm, Intel MPI.

**Comment by danielsuo** [comment]
Ah, I see. Makes sense. Ok, I'll add all those to the "todo" list in
bin/README.md (didn't want to clog up issues for the moment while I get
things going)

**Comment by danielsuo** [comment]
@mihaic Do we want to build documentation into the wheels? It's on the to-do list, but I'm not sure why we want to do that.

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by danielsuo** [comment]
Getting close to where we want to be. Current status [here](https://github.com/danielsuo/brainiak/tree/wheels/bin).

Do we want to package the documentation and other metadata with the ```.whl``` files? It doesn't look too [hard](http://python-packaging.readthedocs.io/en/latest/non-code-files.html), but just wondering.

**Comment by mihaic** [comment]
Jenkins, add to whitelist.

**Comment by mihaic** [comment]
I think we should leave out the docs. Over time, they will grow much larger than the code, considering the images and potentially videos generated by running the example notebooks. Also, similar packages (numpy, scikit-learn, nilearn) do not include docs in their wheels.

**Comment by danielsuo** [comment]
Sounds good!

**Comment by danielsuo** [comment]
For good reason, Travis CI does not run the ```deploy``` step for PRs. Going to push this to the ```wheels``` branch of the main repository until things are sorted out and then merge the history back here.

**Comment by danielsuo** [comment]
I could have also run this on my own fork / closed this PR temporarily. But we have come to far. Such is life.

**Comment by danielsuo** [comment]
Closing this thread, but leaving this branch alive since there are a lot of useful tidbits related to building wheels, managing Travis more programmatically, automating deployment / uploads, etc.

**Pull request closed without merging**
