### PR TITLE
added __all__ to utils

### PR DESCRIPTION
**Pull request by szorowi1**
First contribution to brainiak. Helping with #366

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by szorowi1** [comment]
Good to know! Thanks and apologies for not reading the CONTRIBUTING more closely!

**Comment by lcnature** [comment]
Jenkins, retest this please.

**Comment by lcnature** [comment]
@xoltar Thanks for approving the other PR. It does get rid of testing errors on travis! But I still don't know why two checks are still waiting for results...

**Comment by mihaic** [comment]
Jenkins, add to whitelist.

**Pull request merged**
