### PR TITLE
dev: Blacklist buggy SciPy release

### PR DESCRIPTION
**Pull request by mihaic**

### CODE REVIEW

**Comment by mihaic** [comment]
Jenkins, retest this please.

**Comment by mihaic** [comment]
Not sure. The bug will always be there in SciPy 1.0.0, which the user can have installed for some reason.

**Comment by danielsuo** [comment]
Ah fair enough. Maybe we add a note to some section in the main README
about install troubleshooting? Mostly because people don't really read
error messages...(or documentation for that matter...)

**Comment by mihaic** [comment]
The installation always succeed because Pip enforces `scipy!=1.0.0` when installing BrainIAK. If afterward the user changes the environment in incompatible ways, I think a note in the README will not help.

**Comment by danielsuo** [comment]
Oh really? Even if the user has some other version of the package? Did not
know that.

**Pull request merged**
