### PR TITLE
Check for 'CC' exists first

### LINKED ISSUE #496: install: PackageNotFoundError
When trying to install via anaconda, I get the following error:
DOC: https://brainiak.org/docs/installation.html

`conda install -c brainiak -c defaults -c conda-forge brainiak
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - brainiak

Current channels:

  - https://conda.anaconda.org/brainiak/win-64
  - https://conda.anaconda.org/brainiak/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`

### PR DESCRIPTION
**Pull request by GMerakis**
Fixes #496

### CODE REVIEW

**Review by mihaic — APPROVED** [review]
Thanks for the PR, @GMerakis! It does fix the `NoneType` error you saw in #496. Unfortunately, I suspect you will encounter other issues, because we do not support Windows.
https://github.com/brainiak/brainiak#quickstart

**Comment by GMerakis** [comment]
> Thanks for the PR, @GMerakis! It does fix the `NoneType` error you saw in #496. Unfortunately, I suspect you will encounter other issues, because we do not support Windows.
> https://github.com/brainiak/brainiak#quickstart

ops ur right.
I did run into issues with c++ compiler...
Do u know of any other blockers on Windows support?

**Comment by mihaic** [comment]
Sorry about that. No, I cannot recall other issues. You are welcome to create a new Windows support issue to track the errors you encounter. That would serve as a good starting point for anyone looking to contribute the code required to Windows support.

**Comment by GMerakis** [comment]
Created issue to track windows support: https://github.com/brainiak/brainiak/issues/498
(my alt acc...)

**Comment by mihaic** [comment]
Thanks again for your contribution, @GMerakis!

**Pull request merged**
