### PR TITLE
Updated the paper reference for SS-SRM

### LINKED ISSUE #303: Update SS-SRM paper reference

### PR DESCRIPTION
**Pull request by TuKo**
Fixes #303

### CODE REVIEW

**Comment by TuKo** [comment]
Please, @mihaic would you mind reviewing this? Thanks.

**Comment by mihaic** [comment]
Sorry about the delay, @TuKo. I was waiting for you to update the branch so it passes the tests. Of course, that is not necessary for review, so I'm reviewing now.

**Comment by mihaic** [comment]
You should be able to update the branch and squash it into the master branch yourself.

**Comment by TuKo** [comment]
Oops, sorry, I forgot.

**Comment by TuKo** [comment]
Done

**Comment by mihaic** [comment]
Merged. You could have merged it too.

**Comment by TuKo** [comment]
No without the rights to do it... ;)

**Comment by mihaic** [comment]
I was confused about the rights. You should be able to merge PRs now, like all others who currently have write access.

**Pull request merged**
