### PR TITLE
Unpin scikit-learn and set gamma to auto in SVC tests

### LINKED ISSUE #448: fcma: test_mvpa_voxel_selection fails with scikit-learn 0.22
See https://travis-ci.org/brainiak/brainiak/jobs/620219411

Pinning to <0.22 works, but we should fix the underlying issue.

### PR DESCRIPTION
**Pull request by ariekahn**
Fixes #448 

scikit-learn 0.22 changed the default value of `gamma` in `SVC` to 'scale' from 'auto' (see https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html). This PR should hopefulyl fix the tests using SVC by explicitly setting gamma to 'auto' in line with previous behavior.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by mihaic** [comment]
Jenkins, add to whitelist.

**Comment by mihaic** [comment]
This looks great! Thanks, @ariekahn.

Could you please change the example code as well, in `examples/fcma`?

**Comment by mihaic** [comment]
Thank you very much for your contribution, @ariekahn. It's great to not have to keep this important dependency pinned.

**Pull request merged**
