### PR TITLE
add warning against using `python setup.py install` 

### LINKED ISSUE #318: docs: Warn against running `python setup.py`
It is not the same as `pip install`, as pointed out in issue #315. We should warn users in the documentation.

### PR DESCRIPTION
**Pull request by sameshl**
Add appropriate warning in installation guide

closes #318

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by mihaic** [comment]
Jenkins, OK to test.

**Comment by mihaic** [comment]
@sameshl, thanks for the PR! The failures are unrelated. We are working on fixes and will get back to you when done.

**Comment by sameshl** [comment]
@mihaic Thanks! Looking forward to contribute more here!

**Comment by mihaic** [comment]
Thanks for stepping up to fix the issue, @sameshl.

**Comment by sameshl** [comment]
Glad to help! @mihaic

**Pull request merged**
