### PR TITLE
revise utils.center_mass_exp; additional tests 

### PR DESCRIPTION
**Pull request by QihongL**
1st time doing this... let me know if there is anything wrong! Thanks!

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by mihaic** [comment]
Jenkins, add to whitelist.

**Comment by QihongL** [comment]
Hi, I thought everything is up-to-date... Maybe I'm misunderstanding something? What do you mean by merging?

Here're the checks:

Qihong@:brainiak$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Qihong@:brainiak$ git pull origin master
From https://github.com/QihongL/brainiak
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Qihong@:brainiak$ git merge new-feature
Already up-to-date.
Qihong@:brainiak$ git push origin master
Everything up-to-date

**Comment by mihaic** [comment]
It looks like you found the update button on GitHub. :) Now you should not merge on your computer anymore, because it will create a conflict. In any case, it is not necessary, as I am merging the PR.

Regarding your question, it looks like your master branch is following your fork instead of upstream. Add a new remote for upstream and change your master branch to follow it:
```
git remote add upstream https://github.com/brainiak/brainiak
git branch --set-upstream-to=upstream/master
```

**Comment by mihaic** [comment]
Thanks, @QihongL. Looking forward for working with you more in the future!

**Comment by QihongL** [comment]
I see! Thanks! Sorry about the confusion!

**Comment by QihongL** [comment]
Ah, when I ran `git branch --set-upstream-to=upstream/master`, I got the following message: 

Qihong@:brainiak$ git remote add upstream https://github.com/brainiak/brainiak
Qihong@:brainiak$ git branch --set-upstream-to=upstream/master
error: the requested upstream branch 'upstream/master' does not exist
hint: 
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint: 
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.


It seems that it couldn't find the `master`. Do you know why it happens?

**Comment by mihaic** [comment]
I forgot one step: you also need to fetch the data from the new remote, it is not sufficient to declare it:
```
git fetch upstream
```
This is mentioned in our contributing docs:
https://github.com/brainiak/brainiak/blob/master/CONTRIBUTING.rst#how-to-contribute

**Comment by QihongL** [comment]
Thanks! @mihaic ! I probably missed that step... lol

**Pull request merged**
