### PR TITLE
Searchlight docstring improve

### PR DESCRIPTION
**Pull request by mjanderson09**

### CODE REVIEW

**Comment by danielsuo** [comment]
Not sure what's up, but when I checked out this latest commit and pushed to my fork, Travis decided the code coverage wasn't high enough. See output [here](https://travis-ci.org/danielsuo/brainiak/jobs/336270115)

For comparison, see the output of ```coverage``` for mine (first) and ```brainiak```'s (second). The ```*srm``` family appears to be the culprit.

```
Name                                  Stmts   Miss Branch BrPart  Cover
-----------------------------------------------------------------------
brainiak/__init__.py                      4      1      2      1    67%
brainiak/eventseg/__init__.py             1      0      0      0   100%
brainiak/eventseg/event.py              135      9     42      5    92%
brainiak/factoranalysis/__init__.py       1      0      0      0   100%
brainiak/factoranalysis/htfa.py         241      8     60      8    95%
brainiak/factoranalysis/tfa.py          248      0     40      2    99%
brainiak/fcma/__init__.py                 1      0      0      0   100%
brainiak/fcma/classifier.py             187     10     62      8    93%
brainiak/fcma/mvpa_voxelselector.py      42      6     14      1    88%
brainiak/fcma/preprocessing.py          156      6     70      6    95%
brainiak/fcma/util.py                    23      1      2      1    92%
brainiak/fcma/voxelselector.py          178     11     56      9    91%
brainiak/funcalign/__init__.py            1      0      0      0   100%
brainiak/funcalign/rsrm.py              124     13     48      7    87%
brainiak/funcalign/srm.py               206     18     82      6    91%
brainiak/funcalign/sssrm.py             228     26     66     11    85%
brainiak/hyperparamopt/__init__.py        0      0      0      0   100%
brainiak/hyperparamopt/hpo.py           117      3     56      4    96%
brainiak/image.py                        41      3     16      3    89%
brainiak/io.py                           41      2     16      2    93%
brainiak/isfc.py                         45      4     22      6    85%
brainiak/reprsimil/__init__.py            1      0      0      0   100%
brainiak/reprsimil/brsa.py             1239     68    326     37    92%
brainiak/searchlight/__init__.py          1      0      0      0   100%
brainiak/searchlight/searchlight.py     130     16     72      4    84%
brainiak/utils/__init__.py                1      0      0      0   100%
brainiak/utils/fmrisim.py               531    118    197     39    74%
brainiak/utils/utils.py                 227     16     86     14    90%
-----------------------------------------------------------------------
TOTAL                                  4150    339   1335    174    89%
```

```
Name                                  Stmts   Miss Branch BrPart  Cover
-----------------------------------------------------------------------
brainiak/__init__.py                      4      1      2      1    67%
brainiak/eventseg/__init__.py             1      0      0      0   100%
brainiak/eventseg/event.py              135      9     42      5    92%
brainiak/factoranalysis/__init__.py       1      0      0      0   100%
brainiak/factoranalysis/htfa.py         241      8     60      8    95%
brainiak/factoranalysis/tfa.py          248      0     40      2    99%
brainiak/fcma/__init__.py                 1      0      0      0   100%
brainiak/fcma/classifier.py             187     10     62      8    93%
brainiak/fcma/mvpa_voxelselector.py      42      6     14      1    88%
brainiak/fcma/preprocessing.py          156      6     70      6    95%
brainiak/fcma/util.py                    23      1      2      1    92%
brainiak/fcma/voxelselector.py          178     11     56      9    91%
brainiak/funcalign/__init__.py            1      0      0      0   100%
brainiak/funcalign/rsrm.py              124      4     48      7    94%
brainiak/funcalign/srm.py               206      3     82      5    97%
brainiak/funcalign/sssrm.py             228      5     66     12    94%
brainiak/hyperparamopt/__init__.py        0      0      0      0   100%
brainiak/hyperparamopt/hpo.py           117      3     56      4    96%
brainiak/image.py                        41      3     16      3    89%
brainiak/io.py                           41      2     16      2    93%
brainiak/isfc.py                         45      4     22      6    85%
brainiak/reprsimil/__init__.py            1      0      0      0   100%
brainiak/reprsimil/brsa.py             1239     68    326     37    92%
brainiak/searchlight/__init__.py          1      0      0      0   100%
brainiak/searchlight/searchlight.py     130     16     72      4    84%
brainiak/utils/__init__.py                1      0      0      0   100%
brainiak/utils/fmrisim.py               531    118    197     39    74%
brainiak/utils/utils.py                 227     16     86     14    90%
-----------------------------------------------------------------------
TOTAL                                  4150    294   1335    174    90%
```

**Comment by mihaic** [comment]
This PR has not caused the coverage to go below the threshold. See the Travis results:
https://travis-ci.org/brainiak/brainiak/builds/334847713

I think lowering the threshold further in your code, which is unrelated to this PR.

On a different note, I agree that SRM coverage should be better, but that is also unrelated to your branch.

**Comment by danielsuo** [comment]
I should clarify, Travis is checking the same commit in both, which is why I thought it was weird and flagged. Perhaps I'm mistaken?

**Comment by mihaic** [comment]
You are right. I can see the same results on my machine. Let's continue the conversation in issue #326.

**Pull request merged**
